### ISSUE TITLE
Feature: Alternate "online" detection

### ISSUE THREAD

**Issue by disconn3ct** [WolfwithSword/Bambu-HomeAssistant-Flows#15]
Ping isn't available to NR in my environment (k8s) and for added fun, I have this flow pointed to a mosquitto broker instead of directly to the printer.

I would like to be able to use either a boolean MQTT topic (specifically `$SYS/broker/connection/FOO/state`) or a home assistant switch entity instead.

The NR nodes are easy enough to set up but I'm not sure the best way to integrate with the overall pipeline.

**Comment by WolfwithSword** [comment]
This is something that I struggled with at the start - online detection via ping was the most universally consistent method I could implement within NR's restrictions that required no external setup. If the user was connected via cloud instead, it would check the HTTP API for online detection, then fallback to local IP as well. Not even SSDP was this reliable.

Additionally, it will also come up as offline if the mqtt simply can't be connected to. The online-by-ip was a quick way to find if it were on or off for the most part, to help transition various states.

I don't think in the general pipeline/flow it should have too much custom stuff, such as an mqtt topic used since that's a very niche edge case that requires additional setup that the majority don't have available. I would suggest to either get ping available within your container (should be possible even with a k8s deployment) or to modify that part of the flow manually and re-apply the changes on each update.

There is some setup in the flow already to differentiate a printer ip and printer "real" ip, as a while ago I was testing it if connected to a mqtt broker hub instead of a printer, that way the mqtt nodes can go to that, but the ping command still used the real ip. This might be something you could play around with in your setup by looking at the different configured options in the settings nodes.

**Comment by disconn3ct** [comment]
I would suggest just having an option to disable the "custom stuff" like ping. It could be replaced with an injector placeholder showing the expected payload instead, leaving it to the end user to populate.

**Comment by WolfwithSword** [comment]
> I would suggest just having an option to disable the "custom stuff" like ping. It could be replaced with an injector placeholder showing the expected payload instead, leaving it to the end user to populate.

There'd be no difference between that and keeping the current ping implementation, and having it be the end user that makes their custom hook into it. If it's going to rely on custom changes, I'd rather have the base be as commonly useful as possible.

The printer online state is just a flow variable, so you could disable the ping cmd block, and run your own group of nodes to handle setting that variable and related failsafes for offline set triggering.

But I would like to avoid adding in custom work that is extremely niche and uncommon on an already fragile component of the workflow. I'm surprised though that ping isn't available in your environment, most k8s deployments I've worked with have still had ping work from within containers/pods.
