### ISSUE TITLE
Error on db upload

### ISSUE THREAD

**Issue by Cres09** [WolfwithSword/Bambu-HomeAssistant-Flows#3]
I set up the advanced setup but i can't get it to create and update the prints table. I keep getting the folowing error:

"12/5/2024, 16:04:25[node: Get Printing Time](http://192.168.50.60:1880/#)
msg : string[39]
"error: relation "prints" does not exist"
12/5/2024, 16:04:25[node: Get Printing Amount](http://192.168.50.60:1880/#)
msg : string[39]
"error: relation "prints" does not exist"
12/5/2024, 16:05:48[node: Insert Update (Mat Cost)](http://192.168.50.60:1880/#)
msg : string[39]
"error: relation "prints" does not exist"
12/5/2024, 16:05:48[node: Insert Update (Plate)](http://192.168.50.60:1880/#)
msg : string[39]
"error: relation "prints" does not exist"

I tried to create myself the table in the db and then there are no error, but nothing gets uploaded. 
The energy_readings tables only worked on uploading the data once.

**Comment by WolfwithSword** [comment]
In the db flow, could you try clicking the box next to this "Force Init" node? 

![image](https://github.com/WolfwithSword/Bambu-HomeAssistant-Flows/assets/12175651/2215f253-f303-4def-91e0-757bcba38541)

This should force the DB to be created. Otherwise, the table "should" be created if not exists anytime a print triggers.  In the DB flow, can you tell me what it shows below this node when you start a new print? Maybe check this before clicking the force-init node actually.

![image](https://github.com/WolfwithSword/Bambu-HomeAssistant-Flows/assets/12175651/90f48fe5-89e3-4449-97c8-6d2f1de77b3b)

If it doesn't show anything, or if it does but you're not sure, can you also check these blue nodes that say "60s" 
![image](https://github.com/WolfwithSword/Bambu-HomeAssistant-Flows/assets/12175651/258b1595-3d9d-4f8a-becc-fde7ac1f3bd9)
 
Does it have a green box saying "Success" below them? It could be the HomeAssistant server connection via these nodes is not setup or is having some issue running, thus the prints table never initializes as it doesn't get triggered that a print started properly there.  Make sure the server credentials in it are setup (and if you're using nodered as a HAOS addon, tick that box saying yes), and that in HA you have the "nodered companion" integration too.

If the other nodes seems to show like "Print Started" just fine as a print is actively going on, and the 60s node shows green success and all that, then could you double click on this node here 
![image](https://github.com/WolfwithSword/Bambu-HomeAssistant-Flows/assets/12175651/63b4c13c-dd13-443b-bce8-9e3e63cc2657)

And verify that the "Server" field/dropdown  is the same as selected as the one in the "Get Printing Time", "Get Printing Amount", "Insert Update (Mat Cost) and "Insert Update (Place)" nodes if you double click them?

**Comment by Cres09** [comment]
so, to your questions:
1. the start / end... node doesn't upload.
2. if i click on force init the tables are created correctly but only some data gets uploaded.
3. the 60s node appears as succes. and the mqtt in also as connected.
4. "and if you're using nodered as a HAOS addon, tick that box saying yes" i'm using HAOS and the tick box was already ticked as yes. and i have the companion too.
5. they are the same.

**Comment by Cres09** [comment]
that waws the issue, althought it looked okay. I deleted everything and make it fresh. now works great. Thank your vey much for your help.
